spring:
#  application:
#    name: asBiSystem
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 1 天过期
    timeout: 86400
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.107.129:3306/asbi_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootlyj
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 4
    host: 139.196.107.129
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 1MB
  # rabbitmq 信息
  rabbitmq:
    host: 139.196.107.129
    username: admin
    password: admin
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
server:
  port: 8103
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: AKIDPcggU2K2WnaMCsMdikgP2TrZtALL7lKf
    secretKey: DBvQikdNyoQwRl0CHAqMlvteTCi294zq
    region: ap-shanghai
    bucket: asbi-1307562037
# 要使用的模型ID
ai:
  model:
    model-id: 1660100329896673281
# 鱼聪明SDK
yuapi:
  client:
    access-key: izvszyxh5ndyccuuhkxseft959h37idh
    secret-key: ktek1dp71r257jqfpx173nv98xzwpbi9
# todo 需替换配置
#aliyun:
#  oss:
#    file:
#      endpoint: xxxxxxxxxxxxx
#      keyid: xxxxxxxxxxxxx
#      keysecret: xxxxxxxxxxxxx
#      bucketname: xxxxxxxxxxxxx
pay:
  alipay:
    APP_ID: 9021000123608518
    APP_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCB3Q9e/hx1Au/8Pq7VFGnERoXsq2NVPof5VXu+2ppNFOpJ+ORq/7zMmKRDqkqL5bXkzhySxKSmGMuS9oWKt7Zq7IOfnhvahRige4WVtIBdaTiaSXTxhHFoqXbSaZhZEOGPBDUc+cnItP+fuxhUcAjhQ1s5M5/33ddhWI6oBv/PUkjiYxRsBA2LfflG30IzoZPGBw0wTVqcQSpxzimI5jn5msSoWVxH/t+dFxu7I155H+JhAXpqoV+dW2LcqLY1y23bbAz8U+xmDtL0NZXd5F561wFwvk5DQV7lNnLhEwM64XBSnFs3xhgXrzFaav0+3rqjL/TSCDxYi3dd/qpkDYpdAgMBAAECggEALdAerBRZVa5Dm2lBpEofRe7bMDMGR/xXW86caSgVZzwJqy7y5gxyPnta98QLqG7RTHap/d0BeNcmeiId2mIVKINnq9fLW7u4hGUPK1ESN+H25fckGk/u8k1WbcRyynj6GcoSMrasSPIRe/g1DRS5DT8F35gmxvqsENt8+Cn/9NNB3VWUXB2UJFUbltyx3hdBaWIiKVCoYjIq1Yk4qRfT9RBAjaeWbGDTmANDTM6P5SaRQLBKGdB4Q1JxCintjTvsn1BXmRlo1M5UiWXbJvhobv3PKJMUqPh7OJf49GSPh70VmWT7LrU0wl+Wxz4xZEQ+RF0mowIS0WKuAlG5KGZEAQKBgQC2cVGDhqsKjlOJ9Yk9W/5V815iOsZOb8KZNWz3Old2khRG31J9gp9PmpZS9hjjUbzsa7nILjcYzNMJUqx37NqFOK6pgUW1+fdu9+4tnRK3WyA1Bvd2L9WGXle0KWsXAYJtzoghdJ0uSgT9fJEyKrlLuZfc+jtgF9m9xbfbgPffcQKBgQC2ONNc9+2l9RdNWNy+NlGTNUyXsuIXIFSc1+Iw3SsNq4JauvDbXGmpPwRKc7Pik2Jbvw0c9AQH4T6aEFSP4KocmNowh8zRdZQv0GeZt3p+03cKWXP2ahXgIgd5qgq8bmFXqM/KSUSDJG0oRn+y9RSTIrDzhdrKrOE2FbXwb5S7rQKBgGmjJZqtkD31eSOJm2R+7r5fw0fHVmm2Rowlpilki54pKTp8NqxbxNj33pC81F5TRrvyCEmDkP14I73jM9/gsgqvblrRckbTLNUBE9UvfNXUGsr5dLHnMpCx8cBstwhEJHxmOOZ+OkDCNS99QCk3GcFh/i/CaDzUsowyfqnHfD7RAoGAW72iVEUSZaJOWAesIyuvyEBmTl2mTGRflRNvcpB3E4vMtic2Cgqtu6LZYy57W1A+jdhTHsePm/QAE4qzODixDHK8LwC/0piywZvX/OEOD/ohDZnZsy7X0p7vSoacnx+nbH22F67pimj1d/h+ZDfVYvptQj2a2L1PKW6myeUzaYUCgYBnd5Z9TH9mG2f/LfQiDFaFNMRsSyIycYE+IXookqXFZyy64R6e6xOhpAm+P3hYmIOE10Aj2qaJzGfFV1rGXVl3ahL9Xcif6kD7aR685jezc9QmqJG/N8b/LfgLC+gkhcUdFDJgS+8Gb/F+J4kQrW7sT28Wrid432DxHKDc0E5d+g==
    ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmt8de3Gp17YBEEpvv+PIQq/V//oXauj35wBG2IOZeqj49ddz7rpufUsQk78KTM+T7zV3HrmD5T90i6TGB+FAqnKVj5VBURmpkelqMvWg6y1E1UIZPwbOXvdtLgBdpyjlHeGo5n3lnNQmYvYVQ0XxhtGOAcSZsO62osN3KftfOhPvXvRbM2939GaVBH19jr5+VPvhPpqd0lN5NRZ1CIgOaB7WSrteicFmJqSGQwAsMSqSwdt16h1qoxHICC9nE/fSt20mdNAkT3RPwPD+xlTJJV8uImvfY6am6L9j2KKULfy0p5RSXNp0ndDJIC7G3WBpeiBMMzIuPehchHeNJ5mnQIDAQAB